NIFTY_50 = [
    "RELIANCE.NS", "TCS.NS", "INFY.NS", "HINDUNILVR.NS", "ICICIBANK.NS",
    "HDFC.NS", "WIPRO.NS", "BAJAJ-AUTO.NS", "MARUTI.NS", "SUNPHARMA.NS",
    "BHARTIARTL.NS", "ITC.NS", "KOTAKBANK.NS", "LT.NS", "ULTRACEMCO.NS",
    "AXISBANK.NS", "SBILIFE.NS", "DMART.NS", "TECHM.NS", "TATAMOTORS.NS",
    "TITAN.NS", "HDFCBANK.NS", "NESTLEIND.NS", "POWERGRID.NS", "HCLTECH.NS",
    "BAJAJFINSV.NS", "JSWSTEEL.NS", "INDUSIND.NS", "CIPLA.NS", "GRASIM.NS",
    "NTPC.NS", "DRREDDY.NS", "EICHERMOT.NS", "HINDALCO.NS", "ADANIPORTS.NS",
    "ADANIGREEN.NS", "ASIANPAINT.NS", "BAJAJHLDNG.NS", "BIOCON.NS", "BOSCHIND.NS",
    "DIVISLAB.NS", "BRITANNIA.NS", "COLPAL.NS", "ESCORT.NS", "GAIL.NS",
    "GODREJIND.NS", "GODREJPROP.NS", "GRAPHITE.NS", "IDFCFIRSTB.NS", "INDIGO.NS"
]

# Data configuration
DATA_PERIOD = "5y"  # 5 years of historical data
DATA_INTERVAL = "1d"  # Daily data
